// console.time("total time is:");
// console.log('anand');
// console.log(true);
// console.log(3+7);
// console.log([1,2,3,4,5]);
// console.log({anand:'name',marks:90});
// console.warn('this is warning');
// console.table({anand:'name',marks:90});
// console.timeEnd("total time is:");
// console.assert(345<120 ,'Age>120 is not possible');
// console.error("this is an error");
console.log(typeof(2/0));